feat: allow not uuid aggregate id
PcComponentes/ddd pull request #34
Opened 2022-07-11 13:26 UTC by calmohallag

- allow not uuid aggregate id

2022-07-11 13:40 UTC, ladbsoft requested changes
Aparte de minucias con el inglés, como suelo sacar yo (😊), por mí quedaría aprobado. A ver qué opinan el resto de compis, de otros contextos 😉

2022-07-11 13:40 UTC, ladbsoft commented on src/Util/Message/AggregateMessage.php
> +                        "AggregateId value should be %s instance, %s given",
```suggestion
                        "AggregateId value should be an instance of %s, %s given",
```

2022-07-14 09:00 UTC, ladbsoft approved these changes

2022-07-14 09:01 UTC, merged

2022-07-14 09:14 UTC, FranMoraton commented on src/Util/Message/AggregateMessage.php
> +
el elseif como clausula de guarda y el if nested no me molesta tanto porque va a desparecer